# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx1G
# Fabric Properties
# check these on https://modmuss50.me/fabric.html
minecraft_version=26.2
loader_version=0.19.3
# Mod Properties
mod_version=0.2.0
maven_group=org.betterLostItems
archives_base_name=salts-anti-aliasing
# Dependencies
# check this on https://modmuss50.me/fabric.html
fabric_version=0.154.0+26.2
modmenu_version=20.0.0-alpha.1
sodium_api_version=0.9.1-beta.3+mc26.2
